[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
passes = "8j5vzygvZzkmFAQ186yPbr4vgVGFtSvmFyzE7KVXmB8Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../dev3-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
